### ISSUE TITLE
Application crashes with NoClassDefFoundError

### ISSUE THREAD

**Issue by archie94** [jmrozanec/pdf-converter#3]
Crashlog:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at org.ghost4j.AbstractRemoteComponent.<init>(AbstractRemoteComponent.java:30)
	at org.ghost4j.renderer.AbstractRemoteRenderer.<init>(AbstractRemoteRenderer.java:23)
	at org.ghost4j.renderer.SimpleRenderer.<init>(SimpleRenderer.java:41)
	at pdf.converter.img.ImgCreator.process(ImgCreator.java:33)
	at pdf.converter.PdfConverter.intoImage(PdfConverter.java:30)
	at pdf.converter.Application.main(Application.java:17)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

I am invoking with the following params

```
PdfConverter.convert(new File("/home/arka/papers/du2016.pdf"))
                .intoImage(new File("images.jpg"), 300, 100, 100, ImageFileExtension.JPG);
```

The file path is valid. What am I doing wrong?

**Comment by archie94** [comment]
Thanks! Will check it out :)
