### ISSUE TITLE
Unable to load library 'gsdll64': Native library (win32-x86-64/gsdll64.dll) not found in resource path

### ISSUE THREAD

**Issue by LiangXD** [jmrozanec/pdf-converter#5]
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'gsdll64': Native library (win32-x86-64/gsdll64.dll) not found in resource path ([file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/charsets.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/deploy.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/access-bridge-64.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/cldrdata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/dnsns.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/jaccess.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/jfxrt.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/localedata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/nashorn.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/sunec.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/sunjce_provider.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/sunmscapi.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/sunpkcs11.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/ext/zipfs.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/javaws.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/jce.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/jfr.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/jfxswt.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/jsse.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/management-agent.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/plugin.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/resources.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/jre/lib/rt.jar, file:/C:/Work/b/word-extract/target/classes/, file:/C:/Users/lxd/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/2.1.2.RELEASE/spring-boot-starter-jdbc-2.1.2.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/boot/spring-boot-starter/2.1.2.RELEASE/spring-boot-starter-2.1.2.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/boot/spring-boot/2.1.2.RELEASE/spring-boot-2.1.2.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/spring-context/5.1.4.RELEASE/spring-context-5.1.4.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/spring-aop/5.1.4.RELEASE/spring-aop-5.1.4.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/spring-expression/5.1.4.RELEASE/spring-expression-5.1.4.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.1.2.RELEASE/spring-boot-starter-logging-2.1.2.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar, file:/C:/Users/lxd/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar, file:/C:/Users/lxd/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.11.1/log4j-to-slf4j-2.11.1.jar, file:/C:/Users/lxd/.m2/repository/org/apache/logging/log4j/log4j-api/2.11.1/log4j-api-2.11.1.jar, file:/C:/Users/lxd/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar, file:/C:/Users/lxd/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar, file:/C:/Users/lxd/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23.jar, file:/C:/Users/lxd/.m2/repository/com/zaxxer/HikariCP/3.2.0/HikariCP-3.2.0.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/spring-jdbc/5.1.4.RELEASE/spring-jdbc-5.1.4.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/spring-beans/5.1.4.RELEASE/spring-beans-5.1.4.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/spring-tx/5.1.4.RELEASE/spring-tx-5.1.4.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/org/mybatis/spring/boot/mybatis-spring-boot-starter/2.0.0/mybatis-spring-boot-starter-2.0.0.jar, file:/C:/Users/lxd/.m2/repository/org/mybatis/spring/boot/mybatis-spring-boot-autoconfigure/2.0.0/mybatis-spring-boot-autoconfigure-2.0.0.jar, file:/C:/Users/lxd/.m2/repository/org/mybatis/mybatis/3.5.0/mybatis-3.5.0.jar, file:/C:/Users/lxd/.m2/repository/org/mybatis/mybatis-spring/2.0.0/mybatis-spring-2.0.0.jar, file:/C:/Users/lxd/.m2/repository/mysql/mysql-connector-java/8.0.13/mysql-connector-java-8.0.13.jar, file:/C:/Users/lxd/.m2/repository/org/projectlombok/lombok/1.18.4/lombok-1.18.4.jar, file:/C:/Users/lxd/.m2/repository/junit/junit/4.12/junit-4.12.jar, file:/C:/Users/lxd/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/spring-core/5.1.4.RELEASE/spring-core-5.1.4.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/spring-jcl/5.1.4.RELEASE/spring-jcl-5.1.4.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/com/alibaba/druid-spring-boot-starter/1.1.10/druid-spring-boot-starter-1.1.10.jar, file:/C:/Users/lxd/.m2/repository/com/alibaba/druid/1.1.10/druid-1.1.10.jar, file:/C:/Users/lxd/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar, file:/C:/Users/lxd/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.1.2.RELEASE/spring-boot-autoconfigure-2.1.2.RELEASE.jar, file:/C:/Users/lxd/.m2/repository/org/apache/poi/poi/3.17/poi-3.17.jar, file:/C:/Users/lxd/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar, file:/C:/Users/lxd/.m2/repository/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar, file:/C:/Users/lxd/.m2/repository/org/apache/poi/poi-ooxml/3.17/poi-ooxml-3.17.jar, file:/C:/Users/lxd/.m2/repository/com/github/virtuald/curvesapi/1.04/curvesapi-1.04.jar, file:/C:/Users/lxd/.m2/repository/org/apache/poi/poi-ooxml-schemas/3.17/poi-ooxml-schemas-3.17.jar, file:/C:/Users/lxd/.m2/repository/org/apache/poi/poi-scratchpad/3.17/poi-scratchpad-3.17.jar, file:/C:/Users/lxd/.m2/repository/org/apache/xmlbeans/xmlbeans/3.0.0/xmlbeans-3.0.0.jar, file:/C:/Users/lxd/.m2/repository/org/plutext/jaxb-svg11/1.0.2/jaxb-svg11-1.0.2.jar, file:/C:/Users/lxd/.m2/repository/net/engio/mbassador/1.2.4.2/mbassador-1.2.4.2.jar, file:/C:/Users/lxd/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar, file:/C:/Users/lxd/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar, file:/C:/Users/lxd/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar, file:/C:/Users/lxd/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar, file:/C:/Users/lxd/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/C:/Users/lxd/.m2/repository/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.jar, file:/C:/Users/lxd/.m2/repository/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar, file:/C:/Users/lxd/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar, file:/C:/Users/lxd/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.8/jackson-databind-2.9.8.jar, file:/C:/Users/lxd/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar, file:/C:/Users/lxd/.m2/repository/org/apache/xmlgraphics/xmlgraphics-commons/2.1/xmlgraphics-commons-2.1.jar, file:/C:/Users/lxd/.m2/repository/org/apache/avalon/framework/avalon-framework-api/4.3.1/avalon-framework-api-4.3.1.jar, file:/C:/Users/lxd/.m2/repository/org/apache/avalon/framework/avalon-framework-impl/4.3.1/avalon-framework-impl-4.3.1.jar, file:/C:/Users/lxd/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar, file:/C:/Users/lxd/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.jar, file:/C:/Users/lxd/.m2/repository/net/arnx/wmf2svg/0.9.8/wmf2svg-0.9.8.jar, file:/C:/Users/lxd/.m2/repository/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar, file:/C:/Users/lxd/.m2/repository/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar, file:/C:/Users/lxd/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar, file:/C:/Users/lxd/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar, file:/C:/Users/lxd/.m2/repository/com/thedeanda/lorem/2.0/lorem-2.0.jar, file:/C:/Users/lxd/.m2/repository/com/bit-scout/pdf-converter/1.0.2/pdf-converter-1.0.2.jar, file:/C:/Users/lxd/.m2/repository/joda-time/joda-time/2.10.1/joda-time-2.10.1.jar, file:/C:/Users/lxd/.m2/repository/org/apache/pdfbox/pdfbox/1.8.16/pdfbox-1.8.16.jar, file:/C:/Users/lxd/.m2/repository/org/apache/pdfbox/fontbox/1.8.16/fontbox-1.8.16.jar, file:/C:/Users/lxd/.m2/repository/org/apache/pdfbox/jempbox/1.8.16/jempbox-1.8.16.jar, file:/C:/Users/lxd/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar, file:/C:/Users/lxd/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar, file:/C:/Users/lxd/.m2/repository/net/coobird/thumbnailator/0.4.8/thumbnailator-0.4.8.jar, file:/C:/Users/lxd/.m2/repository/org/ghost4j/ghost4j/1.0.1/ghost4j-1.0.1.jar, file:/C:/Users/lxd/.m2/repository/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar, file:/C:/Users/lxd/.m2/repository/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar, file:/C:/Users/lxd/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar, file:/C:/Users/lxd/.m2/repository/com/lowagie/itext/2.1.7/itext-2.1.7.jar, file:/C:/Users/lxd/.m2/repository/args4j/args4j/2.32/args4j-2.32.jar, file:/C:/Users/lxd/.m2/repository/fr/opensagres/xdocreport/org.apache.poi.xwpf.converter.pdf/1.0.5/org.apache.poi.xwpf.converter.pdf-1.0.5.jar, file:/C:/Users/lxd/.m2/repository/fr/opensagres/xdocreport/org.apache.poi.xwpf.converter.core/1.0.5/org.apache.poi.xwpf.converter.core-1.0.5.jar, file:/C:/Users/lxd/.m2/repository/org/apache/poi/ooxml-schemas/1.1/ooxml-schemas-1.1.jar, file:/C:/Users/lxd/.m2/repository/com/itextpdf/itextpdf/5.5.6/itextpdf-5.5.6.jar, file:/C:/Users/lxd/.m2/repository/fr/opensagres/xdocreport/org.odftoolkit.odfdom.converter.pdf/1.0.5/org.odftoolkit.odfdom.converter.pdf-1.0.5.jar, file:/C:/Users/lxd/.m2/repository/fr/opensagres/xdocreport/org.odftoolkit.odfdom.converter.core/1.0.5/org.odftoolkit.odfdom.converter.core-1.0.5.jar, file:/C:/Users/lxd/.m2/repository/org/odftoolkit/odfdom-java/0.8.7/odfdom-java-0.8.7.jar, file:/C:/Users/lxd/.m2/repository/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar, file:/C:/Users/lxd/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar, file:/C:/Users/lxd/.m2/repository/fr/opensagres/xdocreport/fr.opensagres.xdocreport.itext.extension/1.0.5/fr.opensagres.xdocreport.itext.extension-1.0.5.jar, file:/C:/Users/lxd/.m2/repository/org/kohsuke/args4j/args4j-maven-plugin/2.32/args4j-maven-plugin-2.32.jar, file:/C:/Users/lxd/.m2/repository/args4j/args4j-tools/2.32/args4j-tools-2.32-all.jar, file:/C:/Program%20Files/Java/jdk1.8.0_144/lib/tools.jar, file:/C:/Users/lxd/.m2/repository/org/apache/maven/maven-project/2.0.4/maven-project-2.0.4.jar, file:/C:/Users/lxd/.m2/repository/org/apache/maven/maven-settings/2.0.4/maven-settings-2.0.4.jar, file:/C:/Users/lxd/.m2/repository/org/apache/maven/maven-profile/2.0.4/maven-profile-2.0.4.jar, file:/C:/Users/lxd/.m2/repository/org/apache/maven/maven-model/2.0.4/maven-model-2.0.4.jar, file:/C:/Users/lxd/.m2/repository/org/apache/maven/maven-artifact-manager/2.0.4/maven-artifact-manager-2.0.4.jar, file:/C:/Users/lxd/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.4/maven-repository-metadata-2.0.4.jar, file:/C:/Users/lxd/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-alpha-6/wagon-provider-api-1.0-alpha-6.jar, file:/C:/Users/lxd/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar, file:/C:/Users/lxd/.m2/repository/org/apache/maven/maven-artifact/2.0.4/maven-artifact-2.0.4.jar, file:/C:/Users/lxd/.m2/repository/org/codehaus/plexus/plexus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.jar, file:/C:/Users/lxd/.m2/repository/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar, file:/C:/Users/lxd/.m2/repository/org/apache/maven/maven-plugin-api/2.0/maven-plugin-api-2.0.jar, file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%202017.2.4/lib/idea_rt.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.loadLibrary(Native.java:569)
	at com.sun.jna.Native.loadLibrary(Native.java:544)
	at org.ghost4j.GhostscriptLibraryLoader.loadLibrary(GhostscriptLibraryLoader.java:39)
	at org.ghost4j.GhostscriptLibrary.<clinit>(GhostscriptLibrary.java:36)
	at org.ghost4j.Ghostscript.initialize(Ghostscript.java:323)
	at org.ghost4j.renderer.SimpleRenderer.run(SimpleRenderer.java:105)
	at org.ghost4j.renderer.AbstractRemoteRenderer.render(AbstractRemoteRenderer.java:86)
	at pdf.converter.img.ImgCreator.process(ImgCreator.java:35)
	at pdf.converter.PdfConverter.intoEpub(PdfConverter.java:42)
	at com.cqph.datacenter.wordextract.utils.TestEpub.main(TestEpub.java:25)

**Comment by LiangXD** [comment]
What is going on with this situation? Where is the .dll file used in your program?How can I solve it?Thank you very much！

**Comment by jmrozanec** [comment]
@LiangXD this is first time this issue is reported. Perhaps you can check if GhostScript is installed? Most probably is not installed and is required for this library to function well. You can download it from [this page](https://www.ghostscript.com/download/gsdnld.html). Please let us know if further assistance is required! 😄

**Comment by LiangXD** [comment]
Dear,thank you very much! I have a PDF document,I want to write the contents of this file into a ePub file in the form of text,can you give me some good suggestions? Look forward to your reply!Thank you!


| |


|
|
lxdcqust@163.com
|
签名由网易邮箱大师定制
On 2/12/2019 20:08，jmrozanec<notifications@github.com> wrote：

@LiangXD this is first time this issue is reported. Perhaps you can check if GhostScript is installed? Most probably is not installed and is required for this library to function well. You can download it from this page. Please let us know if further assistance is required! 😄

**Comment by jmrozanec** [comment]
@LiangXD sure - an example is provided in the README. Best!
