### ISSUE TITLE
Unable to delete file

### ISSUE THREAD

**Issue by LiangXD** [jmrozanec/pdf-converter#6]
java.io.IOException: Unable to delete file: C:\Users\lxd\AppData\Local\Temp\26543f4c-1cdb-4b87-94c8-6bb10b98ce235700467008231207745\images\00023.png
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at pdf.converter.epub.EpubCreator.create(EpubCreator.java:47)
	at pdf.converter.PdfConverter.intoEpub(PdfConverter.java:44)
	at com.cqph.datacenter.wordextract.utils.TestEpub.main(TestEpub.java:26)

**Comment by jmrozanec** [comment]
@LiangXD thank you for using pdf-converter! May we ask you for some more contextual information? Ex.: directory and file permissions, if the file exists in the mentioned directory, if directory exists or was deleted already?

Thanks!
