### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by renhaiyan** [jmrozanec/pdf-converter#7]
java.lang.UnsatisfiedLinkError: Unable to load library 'gsdll64': ÕҲ»µ½ָ¶¨
How to deal with

**Comment by jmrozanec** [comment]
@renhaiyan may we ask you for more context and perhaps a test to reproduce the error? Thanks!

**Comment by atkawa7** [comment]
```SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'gs': dlopen(libgs.dylib, 9): image not found
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:166)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:239)
	at com.sun.jna.Library$Handler.<init>(Library.java:140)
	at com.sun.jna.Native.loadLibrary(Native.java:393)
	at com.sun.jna.Native.loadLibrary(Native.java:378)
	at org.ghost4j.GhostscriptLibraryLoader.loadLibrary(GhostscriptLibraryLoader.java:39)
	at org.ghost4j.GhostscriptLibrary.<clinit>(GhostscriptLibrary.java:34)
	at org.ghost4j.Ghostscript.initialize(Ghostscript.java:323)
	at org.ghost4j.renderer.SimpleRenderer.run(SimpleRenderer.java:105)
	at org.ghost4j.renderer.AbstractRemoteRenderer.render(AbstractRemoteRenderer.java:86)
	at pdf.converter.img.ImgCreator.process(ImgCreator.java:35)
	at pdf.converter.PdfConverter.intoEpub(PdfConverter.java:42)
	at test.example.PdfBuilder.main(PdfBuilder.java:12)```

**Comment by atkawa7** [comment]
Solved by installing Ghostscript

**Comment by zhihaozhao123** [comment]
> Solved by installing Ghostscript

I meet too, how did you install?
